# Generated by Django 3.2.6 on 2021-08-16 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0003_auto_20210816_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
