# Generated by Django 3.2.6 on 2021-08-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0005_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(related_name='categories', through='rareapi.PostCategory', to='rareapi.Category'),
        ),
    ]
