# Generated by Django 3.2.6 on 2021-08-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0008_auto_20210816_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='created_on',
            field=models.DateField(default='2021-08-16'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateField(default='2021-08-16'),
        ),
    ]
