# Generated by Django 3.2.6 on 2021-08-16 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0009_auto_20210816_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created_on',
        ),
    ]
